name: Release Linux Binaries
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --draft --generate-notes --title "${{ github.ref_name }}"

  build-assets:
    name: Build Linux release assets
    needs: create-release
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, build_tool: cargo } # Linux x86_64 (glibc)
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu, build_tool: cross } # Linux ARM64 (glibc)
          - { os: macos-latest, target: x86_64-apple-darwin, build_tool: cargo }       # Mac Intel
          - { os: macos-latest, target: aarch64-apple-darwin, build_tool: cargo }      # Mac Silicon
          - { os: windows-latest, target: x86_64-pc-windows-msvc, build_tool: cargo }  # Windows x86_64
          - { os: windows-latest, target: aarch64-pc-windows-msvc, build_tool: cargo } # Windows ARM64

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}
      - name: Build and Upload Asset
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: keeper
          target: ${{ matrix.config.target }}
          build-tool: ${{ matrix.config.build_tool }}
          checksum: sha256
          token: ${{ secrets.GITHUB_TOKEN }}
          include: LICENSE,README.md
