name: Release Binaries
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --draft --generate-notes --title "${{ github.ref_name }}"

  build-assets:
    name: Build release assets
    needs: create-release
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use_cross: false } # Linux x86
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu, use_cross: true }  # Linux ARM64 (RPi)
          - { os: macos-latest, target: x86_64-apple-darwin, use_cross: false }       # Mac Intel
          - { os: macos-latest, target: aarch64-apple-darwin, use_cross: false }      # Mac Silicon
          - { os: windows-latest, target: x86_64-pc-windows-msvc, use_cross: false }  # Windows x86

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}
      - name: Build and Upload Asset
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: keeper
          target: ${{ matrix.config.target }}
          use-cross: ${{ matrix.config.use_cross }}
          token: ${{ secrets.GITHUB_TOKEN }}
          include: LICENSE, README.md
